config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  get '/products/showall', to: 'products#showall', as: 'products_showall'

  resources :products do
    resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :reviews

  validates :name, :presence => true
  validates :cost, :presence => true
  validates :country, :presence => true

  scope :newest, -> { order(created_at: :desc).limit(3) }

  scope :from_usa, -> { where(country: 'USA') }

  scope :most_reviewed, -> {(
    select("products.id, products.*, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(10)
    )}

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :product

  validates :author, :presence => true
  validates :body, :presence => true
  validates_length_of( :body, in: 50..250)
  validates :rating, :presence => true
  validates_numericality_of(:rating, less_than: 6)
  validates_numericality_of(:rating, greater_than: 0)
  validates :product_id, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @newest_products = Product.newest
    @usa_products = Product.from_usa
    @most_reviewed = Product.most_reviewed[0]
  end

  def showall
    @products = Product.all
    @url = request.path_info
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "( product saved )"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    prodName = @product.name
    @product.destroy
    flash[:notice] = "( Product '#{prodName}' deleted )"
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :country)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "review added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:author, :body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RossmannComputerParts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="news">

    <header>
      <div class="nav">
        <ul>
          <li class="home"><%= link_to "Home", root_path %></li>
          <li class="all"><%= link_to "All Products", products_showall_path %></li>
        </ul>
      </div>
    </header>

    <div class="banner">
      <h1>Rossman Computer Parts</h1>
    </div>

    <div class="container">
      <div class="alert-notice">
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </div>

  </body>

</html>

app/views/products/_form.html.erb
<%= render('layouts/errors', :object => @product ) %>

<%= form_for [@product] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :cost %>
  <%= f.number_field :cost, :class => 'text_field', :step => 0.01 %>
  <br><br>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product <%= @product.name %> </h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h2>Products Home</h2>

<br><br>

<h3>Most reviewed!</h3>
<% if @most_reviewed != nil %>
  <ul>
    <li class="home-list">
      <span class="prod-name"> <%= link_to @most_reviewed.name, product_path(@most_reviewed) %></span> |
      <%= link_to "Edit", edit_product_path(@most_reviewed) %> |
      <%= link_to "Delete", product_path(@most_reviewed),
                               :data => {:confirm => "You sure?",
                                         :method => "delete"} %>
    </li>
  </ul>
<% end %>

<h3>New!</h3>
<% if @newest_products != nil %>
  <ul>
    <% @newest_products.each do |product|  %>
      <li class="home-list">
        <span class="prod-name"> <%= link_to product.name, product_path(product) %></span> |
        <%= link_to "Edit", edit_product_path(product) %> |
        <%= link_to "Delete", product_path(product),
                                 :data => {:confirm => "You sure?",
                                           :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% end %>

<h3>Products made in the USA!</h3>
<ul>
  <% @usa_products.each do |product|  %>
    <li class="home-list">
      <span class="prod-name"> <%= link_to product.name, product_path(product) %></span> |
      <%= link_to "Edit", edit_product_path(product) %> |
      <%= link_to "Delete", product_path(product),
                               :data => {:confirm => "You sure?",
                                         :method => "delete"} %>
    </li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h1>Add a new product</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1> <%= @product.name %> - details </h1>
<h3> Price: $<%= @product.cost %> </h3>
<h3> Country: <%= @product.country %> </h3>

<%= link_to "Add a review", new_product_review_path(@product) %>

<br>
<br>

<div class="prod-list">
  <% if @product.reviews.any? %>
    <ul>
      <% @product.reviews.each do |review| %>
        <li>
          <p><%= review.body %></p>
          <p> -- <%= review.author %></p>
          <p>Rating: <%= review.rating %></p>
        </li>
        <br>
        <br>
      <% end %>
    </ul>
  <% else %>
    <p>There are no reviews for this product yet</p>
  <% end %>
</div>

app/views/products/showall.html.erb
<h2>all products</h2>

<%= link_to "Add a product", new_product_path(@product) %>

<br><br>

<ul>
  <% @products.each do |product|  %>
    <li>
      <span id="prod-name"> <%= link_to product.name, product_path(product) %></span> |
      <%= link_to "Edit", edit_product_path(product.id) %> |
      <%= link_to "Delete", product_path(product),
                               :data => {:confirm => "You sure?",
                                         :method => "delete"} %>
    </li>
  <% end %>
</ul>

app/views/reviews/_form.html.erb
<%= render('layouts/errors', :object => @review ) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br><br>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <br><br>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/new.html.erb
<h1>Add a review</h1>

<%= render 'form' %>